version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: backend_db
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"

